spring.application.name=HiringGo

#Spring Database Properties
spring.datasource.url=jdbc:postgresql://localhost:5432/hiring-go
spring.datasource.username=postgres
spring.datasource.password=HarryPotter@123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Spring Security Properties
spring.security.user.name=arth
spring.security.user.password=arth@123